import type { MoneyFunnel } from "./money-funnels";

export const scenarioFunnels = {
  buyBeforeSell: {
    slug: "buy-before-sell",
    eyebrow: "Buy Before Sell",
    title: "Buy the next home without losing the current one.",
    description:
      "Timing, bridge strategy, equity, and payment planning when purchase and sale do not line up cleanly.",
    ogTitle: "Buy before you sell—without guessing the bridge.",
    ogDescription:
      "Understand timing, contingent sale risk, equity access, and financing structure before writing the offer.",
    heroLead: "The next home is right. The timing is not simple.",
    heroFocus: "Bridge timing. Equity. Contingency risk. Next step.",
    videoSlug: "buyer-readiness-before-search",
    videoTitle: "Know the bridge before the offer.",
    videoLead: "Payment and timing clarity reduce last-minute pressure.",
    takeaways: [
      "Purchase and sale timing rarely align perfectly.",
      "Bridge or contingent structures change risk and cost.",
      "Equity and reserves shape what is realistic.",
      "Payment on two homes is a planning problem, not a surprise.",
      "Agents need a financing story before the contingency conversation.",
    ],
    takeawaysEyebrow: "Buyer Lens",
    takeawaysTitle: "What changes when you buy first.",
    takeawaysLead: "Structure the move before the contract clock starts.",
    mistakes: [
      "Assuming the current home will sell on your timeline.",
      "Ignoring carrying cost on two properties.",
      "Waiting until contract to discuss bridge options.",
      "Treating pre-approval as the full strategy.",
      "Skipping reserve planning for both transactions.",
    ],
    mistakesEyebrow: "Timing Risk",
    mistakesTitle: "Where buy-before-sell deals break.",
    mistakesLead: "The issue is usually sequence—not desire.",
    clarifies: ["Bridge timing", "Contingency", "Equity", "Reserves", "Payment"],
    howItWorks: [
      { title: "Map", body: "Sale timeline, purchase timeline, and cash need." },
      { title: "Compare", body: "Bridge, contingent, or staged structure." },
      { title: "Confirm", body: "Payment and reserves on both sides." },
    ],
    ctaLabel: "Review Buy-Before-Sell Options",
    ctaTitle: "Sequence the move with intention.",
    ctaBody: "Send the scenario. We will help frame timing, equity, and structure.",
    formType: "Buyer Strategy Call",
    bookingType: "buyer",
    relatedGuides: [
      { label: "Guide", title: "Buyer readiness", href: "/learn/buyer-readiness" },
      { label: "Guide", title: "Jumbo loans", href: "/learn/jumbo-loans" },
      { label: "Scenario", title: "First-time buyers", href: "/learn/buyer-readiness" },
    ],
    relatedSocialSlugs: ["buyer-readiness-before-search"],
    transcriptPlaceholder:
      "Transcript placeholder for buy-before-sell timing, bridge strategy, and contingent sale planning.",
    faqPlaceholder: [
      "Can I buy before my current home sells?",
      "What is a bridge loan?",
      "How do contingencies affect offer strength?",
    ],
  },
  selfEmployedBorrowers: {
    slug: "self-employed-borrowers",
    eyebrow: "Self-Employed Borrowers",
    title: "Your income story is real—even when the tax return is complicated.",
    description:
      "Bank statement, P&L, and documentation strategy for self-employed buyers and 1099 earners.",
    heroLead: "The business works. The paperwork does not always tell that story cleanly.",
    heroFocus: "Documentation. Averages. Reserves. Structure.",
    videoSlug: "buyer-readiness-before-search",
    takeaways: [
      "Self-employed income is documented differently than W-2 income.",
      "Tax returns may understate cash flow by design.",
      "Bank statement paths exist for the right borrower profile.",
      "Reserves and business stability matter.",
      "Starting early prevents contract surprises.",
    ],
    mistakes: [
      "Waiting until contract to organize documentation.",
      "Assuming one lender path fits every self-employed borrower.",
      "Ignoring business account patterns.",
      "Mixing personal and business deposits without context.",
    ],
    clarifies: ["Documentation", "Averages", "Reserves", "Entity type", "Timeline"],
    howItWorks: [
      { title: "Organize", body: "Accounts, deposits, and business context." },
      { title: "Match", body: "Program path to how you actually earn." },
      { title: "Confirm", body: "Qualification before the offer window." },
    ],
    ctaLabel: "Review Self-Employed Options",
    ctaTitle: "Document the story lenders need.",
    ctaBody: "Send the scenario. We will help frame documentation and structure.",
    formType: "Buyer Strategy Call",
    bookingType: "buyer",
    relatedGuides: [
      { label: "Guide", title: "Jumbo loans", href: "/learn/jumbo-loans" },
      { label: "Scenario", title: "Investment property", href: "/scenarios/investment-property-strategy" },
    ],
    relatedSocialSlugs: ["buyer-readiness-before-search"],
    transcriptPlaceholder: "Transcript placeholder for self-employed documentation strategy.",
    faqPlaceholder: [
      "Can self-employed borrowers qualify without tax returns?",
      "What do bank statement programs look for?",
    ],
  },
  physicianLoans: {
    slug: "physician-loans",
    eyebrow: "Physician Loans",
    title: "Financing that respects how physicians actually build careers.",
    description:
      "Physician, dentist, and resident loan strategy with flexible down payment and student-debt context.",
    heroLead: "Residency, fellowship, and practice transitions do not fit a standard borrower box.",
    heroFocus: "Student debt. Down payment. Transition timing.",
    videoSlug: "buyer-readiness-before-search",
    takeaways: [
      "Physician programs may allow lower down payments for eligible borrowers.",
      "Student loan treatment can differ from conventional paths.",
      "Employment contracts and start dates matter.",
      "Luxury and jumbo overlap is common in physician purchases.",
      "Early strategy improves offer confidence.",
    ],
    mistakes: [
      "Assuming every physician program is the same.",
      "Ignoring future payment after transition.",
      "Waiting until contract to confirm program fit.",
    ],
    clarifies: ["Student debt", "Down payment", "Contract", "Reserves", "Timing"],
    howItWorks: [
      { title: "Confirm", body: "Role, employment, and program eligibility." },
      { title: "Compare", body: "Physician path vs conventional or jumbo." },
      { title: "Plan", body: "Payment, reserves, and offer strategy." },
    ],
    ctaLabel: "Review Physician Loan Options",
    ctaTitle: "Match the program to the career stage.",
    ctaBody: "Send the scenario. We will help frame physician loan fit and structure.",
    formType: "Buyer Strategy Call",
    bookingType: "buyer",
    relatedGuides: [
      { label: "Guide", title: "Jumbo loans", href: "/learn/jumbo-loans" },
      { label: "Scenario", title: "First-time buyers", href: "/learn/buyer-readiness" },
    ],
    relatedSocialSlugs: ["buyer-readiness-before-search"],
    transcriptPlaceholder: "Transcript placeholder for physician loan strategy.",
    faqPlaceholder: [
      "What is a physician mortgage loan?",
      "Do physician loans require PMI?",
    ],
  },
  condoFinancing: {
    slug: "condo-financing",
    eyebrow: "Condo Financing",
    title: "The HOA questions matter as much as the rate.",
    description:
      "Warrantability, reserves, and offer strategy for condo buyers in Seattle-area markets.",
    heroLead: "The unit can be perfect while the project still needs a financing review.",
    heroFocus: "Warrantability. HOA. Reserves. Offer strength.",
    videoSlug: "buyer-readiness-before-search",
    takeaways: [
      "Condo projects have warrantability and investor concentration rules.",
      "HOA financials can affect timing and approval.",
      "Non-warrantable condos require different lender paths.",
      "Urban markets add competition and documentation pressure.",
      "Early review protects the offer timeline.",
    ],
    mistakes: [
      "Assuming every condo finances the same way.",
      "Skipping project review before the offer.",
      "Ignoring HOA special assessments.",
      "Treating condo pre-approval like single-family pre-approval.",
    ],
    clarifies: ["Warrantability", "HOA review", "Reserves", "Down payment", "Timeline"],
    howItWorks: [
      { title: "Review", body: "Project, HOA, and occupancy context." },
      { title: "Confirm", body: "Lender path and documentation." },
      { title: "Offer", body: "Structure with financing confidence." },
    ],
    ctaLabel: "Review Condo Financing",
    ctaTitle: "Confirm the project before the offer.",
    ctaBody: "Send the address and scenario. We will help frame condo financing fit.",
    formType: "Buyer Strategy Call",
    bookingType: "buyer",
    relatedGuides: [
      { label: "Guide", title: "Buyer readiness", href: "/learn/buyer-readiness" },
      { label: "Guide", title: "Jumbo loans", href: "/learn/jumbo-loans" },
    ],
    relatedSocialSlugs: ["buyer-readiness-before-search"],
    transcriptPlaceholder: "Transcript placeholder for condo warrantability and HOA strategy.",
    faqPlaceholder: [
      "What makes a condo non-warrantable?",
      "Can I finance a condo with low down payment?",
    ],
  },
  investmentPropertyStrategy: {
    slug: "investment-property-strategy",
    eyebrow: "Investment Property",
    title: "The property has to work on paper—not just in the pitch.",
    description:
      "Rental income, reserves, and financing structure for buyers scaling investment property.",
    heroLead: "Spreadsheets are easy until underwriting asks different questions.",
    heroFocus: "Rental income. Reserves. Program fit. Scale.",
    videoSlug: "market-context-without-noise",
    takeaways: [
      "Investment property guidelines differ from primary residence.",
      "Rental income treatment varies by program.",
      "Reserves increase with financed property count.",
      "DSCR paths may fit certain rental strategies.",
      "Structure should match hold period and cash-flow goal.",
    ],
    mistakes: [
      "Using primary-residence assumptions on rentals.",
      "Ignoring reserve requirements at scale.",
      "Assuming all rental income counts the same way.",
      "Skipping program comparison before contract.",
    ],
    clarifies: ["Rental income", "Reserves", "DSCR", "Down payment", "Scale"],
    howItWorks: [
      { title: "Define", body: "Hold strategy and property role." },
      { title: "Match", body: "Conventional, DSCR, or commercial path." },
      { title: "Confirm", body: "Cash flow and documentation before offer." },
    ],
    ctaLabel: "Review Investment Strategy",
    ctaTitle: "Make the numbers lender-ready.",
    ctaBody: "Send the scenario. We will help frame rental and investment structure.",
    formType: "Commercial Scenario Review",
    relatedGuides: [
      { label: "Guide", title: "DSCR loans", href: "/learn/dscr-loans" },
      { label: "Guide", title: "Commercial lending", href: "/learn/commercial-lending" },
    ],
    relatedSocialSlugs: ["market-context-without-noise"],
    transcriptPlaceholder: "Transcript placeholder for investment property financing strategy.",
    faqPlaceholder: [
      "How is rental income calculated?",
      "When does DSCR make sense?",
    ],
  },
} satisfies Record<string, MoneyFunnel>;
